### PR TITLE
CLI: Warn when a URL is invalid

### LINKED ISSUE #29: Raise a warning if a URL is invalid
See https://github.com/liip/TheA11yMachine/pull/28#discussion_r49563345.

### PR DESCRIPTION
**Pull request by Hywan**
Fix #29.

### CODE REVIEW

**Comment by Hywan** [comment]
@krtek4 Are you OK with this one?

**Comment by krtek4** [comment]
This is a first step... We should also raise a warning when the crawler cannot access an URL, it is fairly easy to catch those by registering the events `fetch404` and `fetcherror`, eventually `fetchtimeout`

Bug merge this as is and maybe open a new thing.

**Comment by Hywan** [comment]
Done :-).

**Comment by Hywan** [comment]
(`git rebase master`)

**Pull request merged**
